### PR TITLE
Add footer component

### LINKED ISSUE #34: Create footer section for mobile

### PR DESCRIPTION
**Pull request by gmagnenat**
Added a simple footer component

### CODE REVIEW

**Comment by gmagnenat** [comment]
@AbbyNyakara can you add your review to this PR when you have a minute?

**Comment by AbbyNyakara** [comment]
> @AbbyNyakara can you add your review to this PR when you have a minute?

Yes. Sure. I must have missed this. Im just seeing it was 4 days ago!!

**Review by AbbyNyakara — CHANGES_REQUESTED** [review]
Hi @gmagnenat . Since the header and the footer are the exact same thing, can we rename the header component to something else, then reuse it for the footer as well. Instead of creating an entire duplicate component?

**Comment by gmagnenat** [comment]
@AbbyNyakara I confess I had the same thought about header and footer. As it could be potentially quite different components, I think it's fine to have one for each.

**Comment by AbbyNyakara** [comment]
> @AbbyNyakara I confess I had the same thought about header and footer. As it could be potentially quite different components, I think it's fine to have one for each.

@gmagnenat, i see your point. Ill approve it

**Review by AbbyNyakara — APPROVED** [review]

**Pull request merged**
